smalles fixes for beta-client
doccano/doccano-client pull request #71
Opened 2022-06-12 07:43 UTC by leonardlin

# Description
* Fix compile error 'typo' in beta client: 'request' -> 'requests' 
* Add documentation how to use beta-client
* Updated main README.md about broken upload-file in old client.

Fixes # (issue)
#13 #16 #50

2022-06-12 16:23 UTC, david-engelmann commented
This pull request (https://github.com/doccano/doccano-client/pull/71) would cover [this open pull request](https://github.com/doccano/doccano-client/pull/68) as well.

2022-07-22 16:59 UTC, ljades requested changes
Thanks for handling this!

2022-07-22 16:59 UTC, ljades commented on doccano_api_client/beta/tests/test_full_integration_tests.py
> +DOCCANO_PASS = "password"
Can you edit the TODO to make all of these pytest params or ENV variables in the future (actually, that might actually be even better for all three)?

2022-07-27 19:32 UTC, ljades commented on doccano_api_client/beta/tests/test_full_integration_tests.py
> +DOCCANO_PASS = "password"
@leonardlin bumping on this. When we've knocked it out, I'd love to see your PR on the 1.6/1.7 compatibility bump you mentioned in #72 too!

2022-07-28 02:30 UTC, ljades commented
Good to go after black linter is resolved!

2022-07-28 15:30 UTC, ljades approved these changes

2022-07-28 15:30 UTC, merged