span, relation, download examples
doccano/doccano-client pull request #81
Opened 2022-08-04 06:17 UTC by leonardlin

# Description

Download project and examples based on 1.7+ API
Ability to filter for confirmed examples
Added span, span-types, relations, relations-type for NER labeling

Fixes # (issue)
#72

2022-08-04 06:18 UTC, leonardlin commented
@ljades sorry, I know it's not good practice to have such big PRs, but it's been a while since I made those changes.

2022-08-04 16:02 UTC, ljades commented
> @ljades sorry, I know it's not good practice to have such big PRs, but it's been a while since I made those changes.

All good, thank you so much for doing this! Will review it soon

2022-08-04 16:34 UTC, leonardlin commented
will fix the linting errors and need to update some test cases, will update pr soon.

2022-08-08 04:58 UTC, ljades requested changes
Awesome job so far. This is a long PR but it'll be useful for getting up to date with the next version. A few extra things:

1. While you don't have to write as exhaustive tests as I wrote for starters, since there are so many new controllers and components you added, it would be super helpful for tech debt removal and stability if you could write at least some test cases for the controllers for relation, relation_type, span, and span_type. Also, provide reason or replacement for the removed example controller tests.
2. Since there are so many new types, can you add some more documentation to the README? Doesn't need to be too extensive, just provide more examples of the client being used as intended keeping all these controllers in mind.
3. Please update the setup.py as well at: https://github.com/doccano/doccano-client/blob/master/setup.py#L25 . Update where the comment says what versions it is compatible with.
4. Update in the README here as well: https://github.com/doccano/doccano-client/blame/master/doccano_api_client/beta/README.md#L5

Thanks again for getting on this!

2022-08-08 04:58 UTC, ljades commented on doccano_api_client/beta/README.md
> -- Swith to the root of the beta client eg. ./doccano_api_client/beta/
The instructions here for parametrizing the integration test credentials has been removed, but it is still needed right now, no?

2022-08-08 04:58 UTC, ljades commented on doccano_api_client/beta/client.py
> +            "referer": base_url,
For my own curiosity, what is the purpose of this addition? Was the API changed so this is now needed?

2022-08-08 04:58 UTC, ljades commented on doccano_api_client/beta/controllers/example.py
> +        while True:
You may disagree, and let me know if you do, but I'm not a fan of using `while True` here if avoidable. Based on the use of `break` down below, you can probably rewrite this without needing `while True` fairly easily.

2022-08-08 04:58 UTC, ljades commented on doccano_api_client/beta/controllers/project.py
> +        while True:
Same with the `while True` over here

2022-08-08 04:58 UTC, ljades commented on doccano_api_client/beta/models/examples.py
> +    text: str = ""
Can an example text be completely empty? Do we want to support that?

2022-08-08 04:58 UTC, ljades commented on doccano_api_client/beta/tests/controllers/test_example.py
> +    #    @responses.activate
What is the reason for all these commented out test cases?

2022-08-08 04:59 UTC, ljades commented
Oh I just remembered you had mentioned you were gonna update test cases soon, I forgot about that. Yep, take your time!

2022-09-20 07:57 UTC, merged